# Generated by Django 4.2.11 on 2025-04-16 12:55

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_initial', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=30)),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('email_add', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField()),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='me/')),
            ],
            options={
                'db_table': 'personal_information',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_img', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=95, scale=None, size=[1920, 1080], upload_to='proj_images/')),
            ],
            options={
                'db_table': 'project_images',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('tools_used', models.TextField(verbose_name='Tools Used')),
                ('proj_desc', models.TextField(verbose_name='Description')),
                ('scope', models.TextField(verbose_name='Project Scope')),
                ('proj_type', models.CharField(choices=[('Application', 'Application'), ('Creative Work', 'Creative Work')], default='Application', max_length=20, verbose_name='Project Type')),
                ('proj_img', models.ManyToManyField(blank=True, to='portfolio.projectimage', verbose_name='Project Image(s)')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
