# Generated by Django 4.2.11 on 2025-04-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='work_id',
            new_name='proj_id',
        ),
        migrations.AlterField(
            model_name='project',
            name='proj_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Commission', 'Commission')], default='Commission', max_length=20, verbose_name='Project Type'),
        ),
    ]
