# Generated by Django 4.2.11 on 2025-04-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_work_id_project_proj_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.CharField(default=1, max_length=4, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
