# Generated by Django 4.2.11 on 2025-04-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('Illustration', 'Illustration'), ('Design & Branding', 'Design & Branding')], default='Illustration', max_length=20, verbose_name='Project Category'),
        ),
    ]
